feat: add initial bot structure
patrykferenc/plant-helper pull request #10
Opened 2022-12-14 21:36 UTC by AgataLa

2022-12-16 14:55 UTC, legeof008 requested changes
Outside of code I have questions regarding the whole structure as a whole:

- Are these .lu files needed ?
- Are the png and pdf files needed ?

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/.gitignore
> +obj/
Just a small thing, but would you mind adding an enplane in here ? Most CI-CD runners are created to require a space here.

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Controllers/BotController.cs
> +            foreach (var adapter in adapters ?? throw new ArgumentNullException(nameof(adapters)))
I'm not particularly familiar with C# or .NET but is the argument thrown here just a runtime exception ? Do we handle it somehow ?

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Controllers/BotController.cs
> +                throw new ArgumentNullException(nameof(route));
The same situation as before is here. In SpringBoot there is an annotation that rejects empty query parameters with 404 error in response.  I'm just curious if that's a thing in .NET.

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Controllers/BotController.cs
> +                throw new KeyNotFoundException($"No adapter registered and enabled for route {route}.");
Here as well.

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Nuget.config
> +      </configuration>
Endline please

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/PlantHelper.csproj
> +</Project>
Endline please

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/PlantHelper.dialog
> +{
Is this file a part of pre-build or pre-run config ?

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Program.cs
> +        public static IHostBuilder CreateHostBuilder(string[] args) =>
Does this method need to be public ?

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Program.cs
> +}
Endline please

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/PlantHelper.botproj
> +}
Endline please

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Properties/launchSettings.json
> +}
Endline please

2022-12-16 14:55 UTC, legeof008 commented on PlantHelperBot/PlantHelper/Startup.cs
> +        public IConfiguration Configuration { get; }
Does this mean that the variable is private within the scope of the package but has a public getter ?

2022-12-16 19:00 UTC, legeof008 approved these changes

2022-12-17 11:03 UTC, legeof008 approved these changes

2022-12-17 19:06 UTC, patrykferenc approved these changes

2022-12-17 19:07 UTC, merged